### ISSUE TITLE
那个下雨中Love特效, 将"love"换为中文字符,会显示"???" , 是什么原因啊

### ISSUE THREAD

**Issue by heise100** [alphardex/kokomi.js#6]

**Comment by alphardex** [comment]
要中文字符的话就要载入中文字体
```js
const font = await kokomi.loadFont();
```
这一行代码是加载字体的，默认加载的是体积小的英文字体， 要中文的话把`loadFont`的参数改成中文字体路径

而且中文字体的格式要转化为`typeface.json`格式，用 http://gero3.github.io/facetype.js/ 转化一下就行
