### ISSUE TITLE
创建了之后为什么移动到角落，比例会变？

### ISSUE THREAD

**Issue by Muralitob** [alphardex/kokomi.js#9]
<img width="678" alt="image" src="https://github.com/alphardex/kokomi.js/assets/29058614/069b91ea-b92c-406e-b5ce-5821a694fd01">

**Comment by alphardex** [comment]
具体哪个例子，截图只截一半我怎么看得出来

**Comment by Muralitob** [comment]
> 具体哪个例子，截图只截一半我怎么看得出来

比如 base environmet glassMateria...

**Comment by alphardex** [comment]
透视相机就是这样的吧……不如说不变才奇怪
